version: "3"
services:
  api:
    build: ./
    ports:
      - "8000:8000"
    depends_on:
      - db
    container_name: devchallenge-api
  db:
    image: mongo
    ports:
      - "27017:27017"
    container_name: devchallenge-db