GET http://localhost:8000/articles/5f94bf88f4cc4d3c34a2b684
Accept: application/json

###
GET http://localhost:8000/articles
Accept: application/json

###
POST http://localhost:8000/articles
Content-Type: application/json

{
  "content": "When your focus is to improve employee performance, ongoing dialogue between managers and their direct reports is essential. While performance management often involves conducting annual performance evaluations, it does involve more than just that. Many companies don’t do formal performance appraisals anymore. Instead, they encourage one-on-one dialogues in which supervisors hold meetings with employees as a way to facilitate two-way communication and one-on one dialogue. These are done on a quarterly or monthly basis. "
}
