GET http://localhost:8000/duplicate_groups
Accept: application/json

###
GET http://localhost:8000/articles/5f95c11ed2f6692d5c6112c4
Accept: application/json

###
GET http://localhost:8000/articles
Accept: application/json

###
POST http://localhost:8000/articles
Content-Type: application/json

{
  "content": "It is an example text number four"
}
