GET http://localhost:8000/articles/5f94bf88f4cc4d3c34a2b684
Accept: application/json

###
GET http://localhost:8000/articles
Accept: application/json

###
POST http://localhost:8000/articles
Content-Type: application/json

{
  "content": "The legal system is made up of criminal and civil courts and specialty courts like bankruptcy and family law courts. Each court is vested with its own jurisdiction. Jurisdiction refers to the types of cases the court is permitted to rule on. Sometimes, only one type of court can hear a particular case. For instance, bankruptcy cases can be ruled on only in bankruptcy court. In other situations, it is possible for more than one court to have jurisdiction. For instance, both a state and federal criminal court could have authority over a criminal case that is also considered an offense under federal and state drug laws."
}

###
GET http://localhost:8000
Accept: application/json
